# This is a dummy comment to trigger cron schedule
name: Website Status Monitor
on:
  schedule:
    - cron: "*/5 * * * *"  # 每5分钟运行一次，UTC时间
  workflow_dispatch:  # 可选：允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install bs4 requests  # 如果你的脚本需要其他库，比如 `beautifulsoup4`

      - name: Run script
        run: python marukyu-matcha_once.py
